version = 1
SPDX-PackageName = "polari"
SPDX-PackageSupplier = "Florian Müllner <fmuellner@gnome.org>"
SPDX-PackageDownloadLocation = "https://gitlab.gnome.org/GNOME/polari"

[[annotations]]
path = ["AUTHORS", "NEWS", "README.md", "REUSE.toml"]
SPDX-FileCopyrightText = "No rights reserved"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.service.in", "**.client", "**.desktop.in", "data/resources/networks.json"]
SPDX-FileCopyrightText = "Florian Müllner <fmuellner@gnome.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["po/**.po", "help/**/**.po"]
SPDX-FileCopyrightText = "GNOME Translation Teams <i18n@gnome.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["po/LINGUAS", "help/LINGUAS", "po/POTFILES.in"]
SPDX-FileCopyrightText = "No rights reserved"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["help/**.page", "help/**.xml"]
SPDX-FileCopyrightText = "GNOME documentation team <gnome-doc-list@gnome.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["data/metainfo/**.png", "help/**.png"]
SPDX-FileCopyrightText = "No rights reserved"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "flatpak/org.gnome.Polari.json"
SPDX-FileCopyrightText = "No rights reserved"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "flatpak/**.patch"
SPDX-FileCopyrightText = "Florian Müllner <fmuellner@gnome.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"
